### ISSUE TITLE
cannot install due to dependency hell with rstan

### ISSUE THREAD

**Issue by verajosemanuel** [David-Hervas/clickR#1]
Great package! but anytime I have to install it , there's a lot of suffering on installing on linux . The procedure is complex and a dead end.

The issue is:

- clickR depends on **rstan**
- rstan depend on brms
- brms depends on shinystan
- shinystan depends on **rstan**

So I'm unable to install clickR no matter I do.
Would be great not to depend on rstan package

thanks

**Comment by David-Hervas** [comment]
Hi, thanks for your suggestion!

We are working on this. I haven't had any problems installing it on linux, but we are aware of the dependecy hell. The brms dependency (and rstan) is temporal while we are working on an alternative method to estimate WAIC on brms models.

**Comment by verajosemanuel** [comment]
And the procedure you've followed to install on linux is "install.packages("clickR")" or any other step is needed?

**Comment by David-Hervas** [comment]
I think in linux I've only tried the github version. Can you try installing it from github?

`devtools::install_github("David-Hervas/clickR")`

I'll take a look at the linux installation using `install.packages()` this evening

**Comment by verajosemanuel** [comment]
Seems to work installing all dependencies except rstan:

```

Installing rstan
Error in FUN(X[[i]], ...) :
  Invalid comparison operator in dependency: >=
Calls: <Anonymous> ... install -> install_deps -> dev_package_deps -> lapply -> FUN
Execution halted
The command '/bin/sh -c Rscript -e 'devtools::install_github("David-Hervas/clickR")'' returned a non-zero code: 1
```

**Comment by David-Hervas** [comment]
Do you have the latest version of devtools? This error was an issue in a previous version of the devtools package: [https://github.com/hadley/devtools/issues/1247](url)

**Comment by David-Hervas** [comment]
OK, I created a new virtual machine with a fresh installation of ubuntu to check all posible dependencies. You need to install these first from terminal before trying to install clickR with `install.packages()`:

```
sudo apt-get install libssl-dev
sudo apt-get install libcairo2-dev
sudo apt-get install libxml2-dev
sudo apt-get install default-jdk
sudo R CMD javareconf
sudo apt-get install libcurl4-openssl-dev
```
After this, I tried install.packages("clickR") and it worked just fine.

As I said before, we are aware there's a dependency hell right now, specially for linux. We are trying to reduce the number of dependencies.

**Comment by verajosemanuel** [comment]
I've tested using a fresh clean ubuntu Docker image. First four libraries installed ok and java reconf done.

`libcurl4-openssl-dev has no installation candidate.`

workaround:
```

sudo apt-get install -f libcurl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libcurl4-gnutls-dev' instead of 'libcurl-dev'
libcurl4-gnutls-dev is already the newest version (7.52.1-5).


```

but some errors appeared:

```
configure: Starting to install library to /tmp/RtmpyMwzmt/R.INSTALL326694d5d73/nloptr/nlopt-2.4.2
./configure: line 3325: ed: command not found
./configure: line 3327: ed: command not found
./configure: line 3331: ed: command not found
[...]
                ^~~~
/usr/local/lib/R/etc/Makeconf:168: recipe for target 'lang__grammars__expression_grammar_inst.o' failed
make: *** [lang__grammars__expression_grammar_inst.o] Error 1
ERROR: compilation failed for package ‘rstan’
* removing ‘/usr/local/lib/R/site-library/rstan’
[...]
ERROR: dependency ‘rstan’ is not available for package ‘shinystan’
* removing ‘/usr/local/lib/R/site-library/shinystan’

```

and so on till the last error:

```
ERROR: dependencies ‘rstan’, ‘shinystan’ are not available for package ‘brms’
* removing ‘/usr/local/lib/R/site-library/brms’
* installing *source* package ‘ReporteRs’ ...
** package ‘ReporteRs’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (ReporteRs)
ERROR: dependency ‘brms’ is not available for package ‘clickR’
* removing ‘/usr/local/lib/R/site-library/clickR’

```



which version of ubuntu are you running?
here mine:


```
root@ff508acff3e6:/# uname -a
Linux ff508acff3e6 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 GNU/Linux
root@ff508acff3e6:/# lsb_release -r
Release:	9.1
```

**Comment by verajosemanuel** [comment]
But don't worry too much David, I'll keep using the windows machine until you get rid of rstan dependencies. No big deal

**Comment by David-Hervas** [comment]
Dependencies with stan, brms, etc. have been removed while mantaining all functionallity
